### PR TITLE
Route Staging EKS onto the new NAT Gateways

### PR DESCRIPTION
**Pull request by dj-maisy**
## What?
As setting up a route specifically for Civica (for Licensify) would be too cumbersome, it might just be easier to route all of our traffic immediately through the new NAT Gateways. So let's give that a try!

## TF Output
...can be viewed here (if you have permission):  
https://app.terraform.io/app/govuk/workspaces/cluster-infrastructure-staging/runs/run-kxHrtVBKALuKHihc

### CODE REVIEW

**Review by sengi — APPROVED** [review]
I think this is the right approach — easy to revert and avoids the complexity of having a weird special-case route.

**Comment by sengi** [comment]
`s/sl.m/route/`?

**Comment by dj-maisy** [comment]
> `s/sl.m/route/`?

Not sure I follow!

**Comment by sengi** [comment]
Just a bit of an odd choice of words! :)

**Pull request merged**
