### PR TITLE
Rename `eks` and `eks-stage2` Terraform projects

### PR DESCRIPTION
**Pull request by karlbaker02**
This PR renames the `eks` and `eks-stage2` Terraform projects to `cluster-infrastructure` and `cluster-services` respectively. This has been defined in a [recent ADR on splitting the Terraform state](https://github.com/alphagov/govuk-infrastructure/blob/main/docs/architecture/decisions/0003-split-terraform-state-into-separate-aws-cluster-and-kubernetes-resource-phases.md#decision) for the EKS and Kubernetes resources and gives clearer meaning to the intentions of the projects:

- `cluster-infrastructure` is concerned only with setting-up the EKS cluster and all associated AWS resources (such as the worker groups and auto-scaling groups).
- `cluster-services` is concerned only with setting up the Kubernetes resources and configuration, including the `aws-auth` ConfigMap.

As part of this PR, the Terraform state for the existing `eks` and `eks-stage2` projects has been duplicated within the state bucket and renamed appropriately for the renamed projects; once we transition over to using the renamed projects, the old Terraform state files can be deleted.

Testing: have duplicated the existing Terraform state files, renamed them inline with the new project names defined in this PR and then run a Terraform init, refresh and plan for each project - no changes have been detected for each, which is correct as this should be a no-op change.

Trello: https://trello.com/c/dqG4nXn0

### CODE REVIEW

**Review by fredericfran-gds — CHANGES_REQUESTED** [review]
thanks for fixing that. I appreciate the testing.

What is the intention for the CI pipeline to deploy the EKS cluster infrastructure and services?

**Comment by karlbaker02** [comment]
> thanks for fixing that. I appreciate the testing.
> 
> What is the intention for the CI pipeline to deploy the EKS cluster infrastructure and services?

Good point, thanks Fred. I have updated the `EKS` pipeline to point at the renamed Terraform projects contained within this PR.

**Review by fredericfran-gds — APPROVED** [review]
nice work, thank you.

**Review by sengi — APPROVED** [review]
LGTM

**Pull request merged**
